---
parser: "@typescript-eslint/parser"
parserOptions:
  project: tsconfig.json
  sourceType: module
plugins:
  - "@typescript-eslint/eslint-plugin"
  - prettier
  - import
extends:
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "prettier"
  - "prettier/@typescript-eslint"
  - "plugin:prettier/recommended"
  - "plugin:jest/recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:import/typescript"
root: true
env:
  node: true
  jest: true
rules:
  "@typescript-eslint/ban-ts-comment": off
  "@typescript-eslint/interface-name-prefix": off
  "@typescript-eslint/explicit-function-return-type": off
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/explicit-module-boundary-types": off
  class-methods-use-this: 0
  import/prefer-default-export: 0
  import/extensions:
    - error
    - ignorePackages
    - js: never
      jsx: never
      ts: never
      tsx: never
  prettier/prettier:
    - "error"
    - parser: "typescript"
      printWidth: 200
      semi: false
      singleQuote: true
      endOfline: "lf"
      trailingComma: "none"


